### ISSUE TITLE
Ubuntu 16 and CUDA

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#121]
Ubuntu 16 has trouble (softly speaking) when using CUDA < 8.0, an additional flag -D_FORCE_INLINES should be added to NVCC flags in the makefiles for cuda-dependent files.

**Comment by ramirezfranciscof** [comment]
Weeks later, but I don't understand the solution proposed for this problem. @fedepedron ?

**Comment by fedepedron** [comment]
I don't know what happened right back, and I couldn't reproduce the error. I'll be closing this issue.
