### ISSUE TITLE
BUG: Memory "crisis" due to bad allocation for vector

### ISSUE THREAD

**Issue by gonzalodm** [MALBECC/lio#126]
In SCF.f90, inside 'starting guess' subroutine. RMM15 is being used as a work memory for dspev call. It is being allocated as MM but it needs to be of size 3*M. Most of the times MM is bigger than 3*M, but when it is not there are *very difficult to identify* problems:

"free(): invalid next size (fast)"

**Comment by fedepedron** [comment]
@ramirezfranciscof didn't you fix this already?

**Comment by ramirezfranciscof** [comment]
I think so; no more RMM15 inside starting guess (see PR #181)
