### ISSUE TITLE
CUDA matrix multiplications

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#130]
Right now there are subroutines in cublasmath that receive two versions of the transformation matrix (X in the szabo), one is real and the other complex (with imaginary part 0). This is because apparently there are no cublas subroutines for multiplying real and complex matrices (only real vs real or complex vs complex). It is however highly inconvenient to have to define and deal with duplicate matrices in the "science" layer of the code and having to drag them throughout all the intermediate procedures. There should be a better way to deal with this.

[This](https://stackoverflow.com/questions/7619492/multiplying-real-matrix-with-a-complex-vector-using-blas) might be a relevant source.

**Comment by ramirezfranciscof** [comment]
I'm more and more convinced that we need to start trying to hide the implementation of objects inside encapsulated type definitions. This would allow to easily add functionalities to them without complicating already working code.

**Comment by fedepedron** [comment]
I believe this has been somewhat addressed after #295. Will reopen if needed.
