### ISSUE TITLE
Population Analysis

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#136]
Are the population analysis subroutines currently working? Is "ipop" being used for different inconsistent purposes? How many population analysis are there available? Is there an existing way to set them via input?

**Comment by segmentat10nfault** [comment]
Che, el "charge constrain" funciona? (ya se Fran que te pregunte esto el
otro dia pero ahora con la respuesta de Fede no me queda claro)

**Comment by ramirezfranciscof** [comment]
I don't think so. I'm going to try to check it out.

**Comment by segmentat10nfault** [comment]
Nono, tranqui! Lo hago el finde que viene!
Vos ponele pilas a Ehrenfest!

**Comment by fedepedron** [comment]
Fixed in #150 (Mewtwo)
