### ISSUE TITLE
Installation failed on CentOS 7.3 with CUDA 8.0

### ISSUE THREAD

**Issue by librahoo** [MALBECC/lio#139]
Dear all,

I tried to install LIO on my linux machine (CentOS 7.3, CUDA 8.0, Intel parallel studio XE 2017) by

make -j cuda=1 time=1

below are the compiling results:

`
cd lioamber; make;
make[1]: Entering directory `/opt/lio/lioamber'
mkdir -p obj
gfortran  -shared -fPIC obj/liomain.o obj/SCF.o obj/SCFop.o obj/SCF_in.o obj/TD.o obj/dip.o obj/dipmem.o obj/jarz.o obj/magnus.o obj/predictor.o obj/mulliken.o obj/dft_get_mm_forces.o obj/dft_get_qm_forces.o obj/matmuldiag.o obj/init.o obj/init_amber.o obj/lio_init.o obj/lio_finalize.o obj/alg.o obj/drive.o obj/func.o obj/grid.o obj/int1.o obj/int1G.o obj/int2.o obj/int2G.o obj/int3lu.o obj/int3mem.o obj/int3mems.o obj/int3G.o obj/intsol.o obj/intsolG.o obj/intsolGs.o obj/intfld.o obj/intSG.o obj/FixMessRho.o obj/get_unit.o PackedStorage.f obj/garcha_mod.o obj/liokeys.o obj/sysdata.o obj/mathsubs.o obj/maskrmm.o -L../g2g -L/usr/lib -L/usr/lib64 -lg2g -lstdc++ -lm -Wl,-rpath='$ORIGIN/' -Wl,-rpath='$ORIGIN/../g2g' -L/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64 -I/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/include -L/usr/lib -llapack -o liblio-g2g.so
make[1]: Leaving directory `/opt/lio/lioamber'

cd liosolo; make;
make[1]: Entering directory `/opt/lio/liosolo'
gfortran main.f -o liosolo  -I../lioamber/obj -J../lioamber/obj -L../g2g -lg2g -L../lioamber -llio-g2g
../g2g/libg2g.so: undefined reference to `cblas_dsyr'
../g2g/libg2g.so: undefined reference to `cblas_ssyr'
collect2: error: ld returned 1 exit status
make[1]: *** [liosolo] Error 1
make[1]: Leaving directory `/opt/lio/liosolo'
make: *** [all] Error 2
`
It seemed like to make g2g and lioamber are OK, but to make liosolo failed. Something wrong with cblas_dsyr/cblas_ssyr. 

Could anyone help me how to fix this issue? Thanks!

Zhenquan

**Comment by segmentat10nfault** [comment]
Dear Zhenquan,

it seems that there is something wrong with your dependences.  When I look
into the linking line I see that you are using intel libraries but at the
same time you are using the GNU compiler. That is probably the problem.

Try compiling with the option intel=1 (or if you want to use the GNU
compilers you can install a free version of LAPACK)

All the best,

Uriel

**Comment by librahoo** [comment]
Dear Uriel, 

Thank you for your help!

However, when I tried with
make -j cuda=1 time=1 intel=1 ifort=1
(It seemed like the ifort=1 option must be added  as well)

New error reported:
`
cd lioamber
...
...
ifort  -shared -fPIC obj/liomain.o obj/SCF.o obj/SCFop.o obj/SCF_in.o obj/TD.o obj/dip.o obj/dipmem.o obj/jarz.o obj/magnus.o obj/predictor.o obj/mulliken.o obj/dft_get_mm_forces.o obj/dft_get_qm_forces.o obj/matmuldiag.o obj/init.o obj/init_amber.o obj/lio_init.o obj/lio_finalize.o obj/alg.o obj/drive.o obj/func.o obj/grid.o obj/int1.o obj/int1G.o obj/int2.o obj/int2G.o obj/int3lu.o obj/int3mem.o obj/int3mems.o obj/int3G.o obj/intsol.o obj/intsolG.o obj/intsolGs.o obj/intfld.o obj/intSG.o obj/FixMessRho.o obj/get_unit.o PackedStorage.f obj/garcha_mod.o obj/liokeys.o obj/sysdata.o obj/mathsubs.o obj/maskrmm.o -L../g2g -L/usr/lib -L/usr/lib64 -lg2g -lstdc++ -lm -Wl,-rpath='$ORIGIN/' -Wl,-rpath='$ORIGIN/../g2g' -L/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64 -I/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/include -L/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64 -I/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/include -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -o liblio-g2g.so
make[1]: Leaving directory `/opt/lio/lioamber'
cd liosolo; make;
make[1]: Entering directory `/opt/lio/liosolo'
ifort main.f -o liosolo  -module ../lioamber/obj -L../g2g -lg2g -L../lioamber -llio-g2g
../lioamber/liblio-g2g.so: undefined reference to `matmul_mkl_f64_'
make[1]: *** [liosolo] Error 1
make[1]: Leaving directory `/opt/lio/liosolo'
make: *** [all] Error 2
`
Any further suggestions?

**Comment by librahoo** [comment]
Done!
By modifying make_links.mk in the lioamber folder, 
adding option -qopt-matmul to LFLAGS, the program could be compiled successfully.

**Comment by fedepedron** [comment]
Dear Zhenquan, 

Thank you for taking a try at our code, I'm glad you were finally able to compile it . I strongly suggest, however, to take a look at the rc (release candidate) branch (do "git checkout rc" before compiling) which brings quite a lot of improvements over the old master branch. It is currently in beta state, but it will be merged with master soon enough.

Should you need any help running please do let us know

Federico

**Comment by librahoo** [comment]
Dear Federico,

Thank you for your update.
However, I could not compile the rc version on my system. command:
`make -j time=1 cpu=0 cuda=1 intel=2`

Results:
`make -C lioamber
make[1]: Entering directory `/opt/lio/lioamber'
Creating new Makefile.log
mkdir -p obj
...
...
...
ifort  -fPIC -Dpack -DG2G -DTD_SIMPLE -fpp -module obj -O1  -c SCFop.f -o obj/SCFop.o
ifort  -fPIC -Dpack -DG2G -DTD_SIMPLE -fpp -module obj -O3  -c TD.f90 -o obj/TD.o
ifort  -fPIC -Dpack -DG2G -DTD_SIMPLE -fpp -module obj -O3  -c predictor.f -o obj/predictor.o
ifort  -fPIC -Dpack -DG2G -DTD_SIMPLE -fpp -module obj -O3  -c dft_get_mm_forces.f -o obj/dft_get_mm_forces.o
ifort  -fPIC -Dpack -DG2G -DTD_SIMPLE -fpp -module obj -O3  -c dft_get_qm_forces.f -o obj/dft_get_qm_forces.o
SCFop.f(180): error #6633: The type of the actual argument differs from the type of the dummy argument.   [E1S]
          call intsol(E1s,Ens,.true.)
----------------------^
SCFop.f(180): error #6633: The type of the actual argument differs from the type of the dummy argument.   [ENS]
          call intsol(E1s,Ens,.true.)
--------------------------^
compilation aborted for SCFop.f (code 1)
make[1]: *** [obj/SCFop.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/opt/lio/lioamber'
make: *** [liblio] Error 2
`

**Comment by fedepedron** [comment]
Dear Zhenquan,

Thank you for pointing that out, regrettably it was a bug included in one of the last PRs. Sorry for the delay, it should be fixed now!

**Comment by librahoo** [comment]
Dear Federico,

Thank you for your update. This time I tried with 
make -j time=1 cpu=0 cuda=1 intel=2 sm52=1
and it works!

**Comment by fedepedron** [comment]
That's great news! Thank you again for trying the code, please recommend it if you find it useful!
