### ISSUE TITLE
lio-rc failed to run with cuda 8.0 and intel compiler v15

### ISSUE THREAD

**Issue by librahoo** [MALBECC/lio#149]
After compiling successfully for lio (rc version) with cuda 8.0 and intel compiler version 15 by
make -j time=1 cpu=0 cuda=1 intel=2 sm52=1
I tried to compile amber16 with -lio, no error reports, however, when I go to directory
$AMBERHOME/test/qmmm_EXTERN/QMMM_Lio/water
and tried to run the test: Run.water & Run.td.water, the program failed:
*** Error in `../../../../bin/sander': free(): invalid next size (normal): 0x0000000017914130 ***
Aborted (core dumped)
possible FAILURE:  file mulliken does not exist.

Any suggestions?

**Comment by fedepedron** [comment]
I believe the problem lies within the fact that many changes have been made to how LIO writes outputs (even input reading has been changed, but we keep backwards-compatibility with AMBER for now) . 

Try to run the test in lio/testamber/badamber, changing the "qm_theory='PM3'" for qm_theory='extern'" lines in the *.in files.

**Comment by fedepedron** [comment]
Glad everything ran properly (by the way, I don't believe the flag specifying smXX is necessary, proper architecture should be automatically selected.).

Regarding the study you want to perform, regrettably we do not have tutorials on our side, but it's not different as performing QM/MM in AMBER with any other method. Just take these into account:

* In your amber input file, remember to add qm_theory='extern' and the following lines 
&lio
/
(this is needed for AMBER to work, it needs the lio namelist although it can be empty)

* If you want to delve deeper into LIO options (the defaults should be OK), create in your working directory a file named "lio.in" and containing the same "&lio /" namelist. 

We will be writing a LIO manual (well, expanding the existing one) in the near future, but please do ask us if you need a specific setup.
