### ISSUE TITLE
Double definition of "partition" object

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#164]
The "Partition" object called "partition" is defined both outside of the namespace G2G in init.cpp and inside the namespace G2G in partition.cpp. Apparently, the second object is not used (it compiles correctly when deleted, @fedepedron is checking if it runs normally), but it is not clear to us why there are two definitions of the object. Does anybody know why is this? ( @manuelF )

**Comment by fedepedron** [comment]
Indeed, that second definition within g2g does not serve any (visible) purpose, LIO runs normally without that line.

**Comment by fedepedron** [comment]
Due to lack of answers, I will be closing this.
