### ISSUE TITLE
Extracting the real/imaginary parts of complex

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#165]
I think the way in which we are extracting the real and imaginary part of complex numbers in the code is not correct. We are using the intrinsics `real` and `aimag`, which apparently convert the number to simple precision. It seems to me that we should be using `realpart` and `imagpart`.

[Source here](https://gcc.gnu.org/onlinedocs/gcc-3.3.6/g77/REAL_0028_0029-and-AIMAG_0028_0029-of-Complex.html).

**Comment by fedepedron** [comment]
Intel compilers do not recognize realpart and imagpart functions. We should write our own sub/function that performs this stuff.

**Comment by fedepedron** [comment]
Further investigation lead to this: according to [gfortran documentation](https://gcc.gnu.org/onlinedocs/gcc-4.3.3/gfortran/AIMAG.html), realpart/imagpart and imag/dble are OLD F77 standards. In modern standards, you have AIMAG and DIMAG; and in real you can specify the precision of the real part obtained (real(x,8) returns the real part of x in double precision).

**Comment by fedepedron** [comment]
I am taking a look at the code and there are no issues with these conversions, so I will be closing this issue for now.
