### ISSUE TITLE
Open Shell is crashing with intel=2

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#170]
Error inside Ex-Corr calculation of fock (g2g_solve_groups). In my case example, a NaN appears in RMM, Fock_beta position 30705, after the call to solve_groups. I will try to check if I can see further into it, else we can check it when you come back @fedepedron .

**Comment by fedepedron** [comment]
Some sort of black sorcery here. I believe it is best to await the SCF-SCFop merger to fix this.

**Comment by fedepedron** [comment]
Just for the record, OpenShell calculations for NO when using intel compiler report NaNs everywhere, while the systems runs perfectly with Gfortran.

**Comment by fedepedron** [comment]
We should have a look at this now that we have #200

**Comment by fedepedron** [comment]
Update: Seems to be fixed in #206, will test shortly.

**Comment by fedepedron** [comment]
Seems fixed, will reopen if this issue reappears.
