### ISSUE TITLE
SCF problem when running H2 molecule

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#179]
- [ ] Apparently found by @gonzalodm . Please do provide me with the problematic example so I can test it.

- [ ] Also, I was informed we should also check runs from amber when changing SCF. I will use my badamber tests to check that nothing was broken during the last SCF modifications.

**Comment by fedepedron** [comment]
Just delete the Oxygen atom in agua_GPU test.

**Comment by fedepedron** [comment]
Update: Happens with cuda=1 while using aint module. Maybe it is a problem with this.

**Comment by fedepedron** [comment]
Fixed in #188.
