### ISSUE TITLE
Switching cuda=1 and cuda=2 options.

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#185]
Since CUBLAS in included in CUDA by default, we should merge both options or at least switch them if we want to keep them for testing purposes.

**Comment by ramirezfranciscof** [comment]
What do you mean "switch them"?

**Comment by fedepedron** [comment]
By "switch them" I mean to exchange their scope:
cuda=1 => cuda + cublas
cuda=2 => only cuda (for testing purposes).

**Comment by fedepedron** [comment]
Added cuda=2 as default in #193.
