### ISSUE TITLE
Testamber broken

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#197]
So, apparently something broke in testamber somewhere in the last months. I'm not sure how much of this is specific to the test or how much is a more general amber interface breakdown. It might be as stupid as a keyword lack of update, but I'll have to check it out.

0fb304d1f5a6fdb9951729f0dc468aeb0b383555 - Working
("Ehrenfest now supports multiple time steps.")
f15bd36b52836645220eadd2ae7eeb91aaf19542 - Wrong numbers
("Ehrenfest PR02 - Incorporation of multiple time-step scheme.")
RC HEAD - Directly broken.

**Comment by ramirezfranciscof** [comment]
Atompot PR0 still works

**Comment by fedepedron** [comment]
Good thing the test is broken and not the main code :stuck_out_tongue:

**Comment by ramirezfranciscof** [comment]
For the record:
06c22a2b18de732c568312201d4a15e4bc8fc5f7 (Pop analysis) => Good numbers
339f549f1bf74019983c79c00101392c73d11418 (DFTB pr 0) => Wrong numbers

Now to check where's the problem, I might eventually need @charlyqchm assistance.

**Comment by fedepedron** [comment]
This is actually worse than we thought, forces calculation are not working propperly.

**Comment by ramirezfranciscof** [comment]
Yes indeed.
