### ISSUE TITLE
Hide all fock calculations inside maskrmm

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#205]
I'm thinking about organizing the calls to RMM in the following fashion. The idea would be to identify all factor that influence in the calculations of each section and **provide them as explicit arguments**. Please check if this organization suits all the code: for example, I know @diegoarmino wants to be able to just calculate overlap for a different basis, so we might achieve this by calling rmmCalc_core with an empty nuclear positions vector for example.

* **rmmCalc_core():** For the calculation of the parts that only depend on the nuclear positions.
  * Subs called: int1, int2, int3mem, g2g_reload_atom_positions, ECP_fock, aint_new_step, intsol, aint_qmmm_fock, aint_coulomb_init.
  * Outputs: Hmat (core fock), e1 (core energy), e1s (elec-solv energy), ens (nuc-solv energy).
  * Inputs: basis set data, nuclear positions.
* **rmmCalc_fock():** For the calculation of the parts that only depend on the current density.
  * Subs called: int3lu, g2g_solve_groups, intfld.
  * Outputs: Fmat ("full" fock), e2 (coulomb energy), exc (xc energy), efld (elec field energy).
  * Inputs: basis set data, nuclear positions, electronic density, electric field.
* **rmmGrad_core:** idem but for the gradient (int1G, intSG)
* **rmmGrad_fock:** idem but for the gradient (int3G, intEG => ehrenfest)

This will probably **decrease** performance because I will be copying the arguments in the corresponding variables of garcha_mod and then copying the results back. Hopefully, the impact will be negligible, and should be recover once we pass the variables as arguments to the corresponding subroutines (ie: the int subroutines).

**Comment by ramirezfranciscof** [comment]
On second thought, I would probably just keep these without providing the basis set as input, so we can have a different subroutine (or a direct call to int1) for @diegoarmino requirements. I think it would be easier to go reverse order there: first having the ints (and g2g) receive the basis as input.

**Comment by fedepedron** [comment]
I believe this is part now of #237.
