### ISSUE TITLE
Forces calculation bug

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#211]
Forces calculation is not working properly. You only need to change the basis set in 0_aguaCPU test to 6-31G**, and you will get NaNs in the forces file. I tried to backtrace this but seems to be an old bug, which happens only in gpu code (cpu-only works fine) while using AINT module.
I will check this in the near future (tomorrow) and see what happens.
-- EDIT --
It only fails with AINT_GPU_LEVEL=5, which in aint module means "!cpu_fit_dens" in coulomb.calc_gradient

**Comment by fedepedron** [comment]
Update: The problem is not within AINT itself, but within the fortran part when MEMO becomes false.

**Comment by nanolebrero** [comment]
when the code is used in fortran the variable MEMO must be T. I do not
understand how it arrived until the calculation of forces with MEMO = F.

**Comment by fedepedron** [comment]
You mean forces calculation MUST set MEMO to true? Meaning, int3mem is essential for forces calculation?

> if (igpu.eq.5) MEMO = .false.

This line has been SCF ever since the creation of the AINT module.

**Comment by nanolebrero** [comment]
Se pone falso cuando no usa el código en fortran que es con aint < 3
(creo). Con aint=5 es correcto que esté falso.
Pero entonces si es un problema en AINT, o al menos eso parece.

**Comment by fedepedron** [comment]
Update: When running with intel, there are no NaNs but the force calculation is not consistent. Also, changing the fitting set works, although the right combination depends on the basis set desired.

**Comment by fedepedron** [comment]
Redundant with #232
