### ISSUE TITLE
Int1 modifications

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#213]
Int1, while currrently  modified to accept RMM variables as input, needs some cleanup. The following issues need to be addressed:

- [x] somehow, nshell is still called from garcha_mod.
- [x] variables a, r, c, d, RMM, Smat and ncont have their size set already, they should not be declared as allocatable.
- [x] commented out code should be removed.
- [x] heavy variable cleanup is needed. For example, Iaux is never used. I suggest removing variables one by one (or in groups) and then checking if the file compiles or not.
- [x] improve documentation, providing a short explanation for inputs and outputs.

**Comment by ramirezfranciscof** [comment]
You can start with this, but I'll probably be adding a couple of things when I get some.

**Comment by diegoarmino** [comment]
Done! PeRreando!

**Comment by fedepedron** [comment]
Fixed in #216.
