### ISSUE TITLE
ABP - Analysis and Brainstorming

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#220]
Ok, lets first start by remembering how did this use to work and how it should be re-implemented. This issue should spawn the more specific tasks.

- fterm_biaspot.f90 has an old subroutine that doesn't seem to be used anymore anywhere. I think it is safe to delete this.

- fockbias_subs and fockbias_data should have all that is needed to use this feature (not digging the names right now, but I will try to resist the urge of constantly renaming stuff). Those have a description of what each variable and subroutine does. Check it and ask any questions here.

From what I can see this...should be working in SCF closed shell? Open shell should only require to make a copy [this line](https://github.com/MALBECC/lio/blob/5d573316ce29384b4b4f4d539b9d4f13bdca6c4e/lioamber/SCF.f90#L621) for the fock_b0. Lets test this trying to polarize some easy molecule.

**Comment by segmentat10nfault** [comment]
Pueden explicar un poco mejor a que se refieren con que el bias simetrico
genera una distribucion asimetrica de cargas de Mulliken?


On Tue, May 29, 2018 at 6:26 PM, Ignacio Pickering <notifications@github.com

**Comment by IgnacioJPickering** [comment]
Si, aplicar un bias solamente sobre los carbonos del eteno genera que los hidrogenos unidos a un mismo carbono adquieran distintas cargas de mulliken.

**Comment by segmentat10nfault** [comment]
Estamos hablando de un cálculo single point con potencial?

**Comment by segmentat10nfault** [comment]
(por potencial me refiero a bias)

**Comment by ramirezfranciscof** [comment]
Can you provide explicitly the input with the bias to each atom and the resulting mulliken populations?

**Comment by charlyqchm** [comment]
In the subroutine fockbias_setmat, the matrix "fockbias_matrix" is builded, then this is added to fock matrix. fockbias_matrix must be symmetric respect to the principal diagonal, right?

**Comment by ramirezfranciscof** [comment]
I would say yes. It is not? Then there could be a problem with the subroutine.

**Comment by charlyqchm** [comment]
I'm checking this and apparently this matrix is asymmetric. The ij element
is not equal  to ji element. I printed this matrix using as bias value
"1.00" on all atoms, to only get the elements of sqsmat, and this is not
symmetric.

2018-05-30 12:40 GMT-03:00 ramirezfranciscof <notifications@github.com>:

**Comment by ramirezfranciscof** [comment]
[This](https://github.com/MALBECC/lio/blob/4c0f5bb909ecf636bb9c8a52291015822fa06c99/lioamber/fockbias_subs.f90#L108-L116) is where fockbias is constructed, and if you used 1 as the bias in all atoms, it should be multiplying the sqsm by itself, thus reconstructing the overlap matrix. You say this is not the case. Can you check that fockbias_setmat is actually eating the sqsmat?

**Comment by fedepedron** [comment]
> Can you check that fockbias_setmat is actually _eating_ the sqsmat?
Just came to highlight this.

**Comment by ramirezfranciscof** [comment]
Subroutines eat variables. That's the technical jargon, as far as I'm concerned. I'll let you deduce how I call the act of returning outputs.

**Comment by charlyqchm** [comment]
[Here]( https://github.com/MALBECC/lio/blob/4c0f5bb909ecf636bb9c8a52291015822fa06c99/lioamber/SCF.f90#L417) fockbias_setmat eat tmpmat, and this is output of overop%Gets_orthog_2m. sqsmat nor tmpmat are symmetric.

**Comment by ramirezfranciscof** [comment]
I like that the outputs of the previous subroutine are tmpmat and sqsmat, the dummy of fockbias_setmat is sqsmat, but somehow SCF is providing tmpmat instead.

From looking inside Gets_orthog_2m, I would think that [this subroutine](https://github.com/MALBECC/lio/blob/4c0f5bb909ecf636bb9c8a52291015822fa06c99/lioamber/SCF.f90#L421) needs to eat a 2 instead of a 3 as first parameter. Do that and check that tmpmat and sqsmat are the same and that doing sqsmat*sqsmat returns the overlap matrix.

**Comment by charlyqchm** [comment]
Solved, matrices are symmetric. Now I'm going to check the effect of the bias.

**Comment by diegoarmino** [comment]
Programar es tan natural como comer y descomer.
