### ISSUE TITLE
TODO - Ehrenfest PR2.0

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#227]
I'm going to accumulate some task to do for the next ehrenfest PR in this issue. If somebody has any request, he/she may put it here.

- [x] Delete ehrentest_SCF.f90; it was a copy of SCF with some tests for ehrenfest and I should have never included that in a PR.
- [x] Delete fterm_biaspot.f90; atomic fock bias potentials have their own module and that is what should be used in all cases.

**Comment by fedepedron** [comment]
This issue seems to be already resolved, closing.
