### ISSUE TITLE
Convergence issues

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#229]
I am seeing a lot of problems with DIIS in openshell; for example, it is quite imposible to converge an H2 molecule in openshell. Maybe we should set hybrid_converg by default? It is slower but more secure.

**Comment by charlyqchm** [comment]
It's more prolix and healthy.

2018-06-18 16:13 GMT-03:00 Federico N. Pedron <notifications@github.com>:

**Comment by fedepedron** [comment]
Another example, fluorine cation (charge=+1, nunp=2) does not converge with diis in 1000 steps, and converges with damping in 79 steps.

**Comment by ramirezfranciscof** [comment]
> It's more **prolix** and healthy.

First Reaction: spanglish WTF?
Google: Well, [that actually exists](http://www.dictionary.com/browse/prolix)...

Back on topic: Was it possible to converge them in less iterations in previous versions of the code?

**Comment by fedepedron** [comment]
Renamed to widen the spectra. I am currently facing _yet again_ problems with my heme-trp system. Essentialy I am in a loop where the system converges and I pick the resulting density, restart the calculation, and then runs hundreds of steps to a **even lower energy**. Rinse and repeat.

**Comment by fedepedron** [comment]
Update: This convergence issues are drastically reduced when running CPU-only. My greatest suspect is yet again G2G GPU code; tune in soon for more updates.
