### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#230]
I believe the current status of LIO is enough to make a proper release, since it has a lot of (supposedly) working functionalities. I would like to propose the deadline of 31/July to freeze current RC and begin stress-testing it. The only changes available to rc will be then bugfixes, writing of the Manual, and _only exceptionally_, small new functionalities (I am thinking of tdanalyze improvements).

Please note that this will probably leave out of the release the libxc functionality (to be merged in 2.1) and posible libint/triple-electrode developments.

A tentative schedule after RC-freezing would be:
* Creation of a develop/nightly branch of LIO for daily updates.
* Update of Manual and bugfixes to RC.
* Periodically merging nightly builds with current RC _on nightly_, not on RC.
* After everything is properly set, major refactor in LIO filesystem.

Opinions?

**Comment by nanolebrero** [comment]
Excellent! agree 100%

**Comment by ramirezfranciscof** [comment]
> Periodically merging nightly builds with current RC on nightly, not on RC.

I didn't understand this, please expand.

**Comment by fedepedron** [comment]
Since probably RC and nightly will be receiving simultaneous update (say, "fixed Open Shell" in RC and "added libint support" in nightly), nightly should be prediocally rebased to current RC to avoid future conflicts.

**Comment by ramirezfranciscof** [comment]
Ohh, ok, rebasing nightly from RC. BTW: why nightly instead of develop? Where did this jargon come from?

**Comment by fedepedron** [comment]
It can be called "develop". I am used to the term "nightly" from the videogame sphere, it actually refers more to the build process (control/codequality/compilation) than to the source code itself. [Relevant wikipedia article](https://en.wikipedia.org/wiki/Neutral_build)

**Comment by fedepedron** [comment]
Ok, now RC is effectively frozen. Manual completion is under way. we only need @gonzalodm's tests.
