### ISSUE TITLE
Purpose of "configure" script

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#246]
Hey @manuelF , I've recently been thinking that it would be much more convenient to have a configure script to set up the makefiles and just run "make" instead of giving the flags each time we compile, and now I've recently noticed you added an empty configure script when you included the travis integration. What was the purpose of this script?

**Comment by manuelF** [comment]
./configure was added to have a trivial travis configuration. 

https://docs.travis-ci.com/user/languages/cpp/#default-build-script

Feel free to repurpose it.

**Comment by ramirezfranciscof** [comment]
@manuelF Thanks!
