### ISSUE TITLE
Convergence issues with CUBLAS

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#256]
If currently facing some issues when using CUBLAS compilations; mainly the cublas version of conver subroutine is not working as expected. Every time I run the same system, I find different energies and densities for the same iteration steps, sometimes even converging to different states. 

I'll take a deeper look into it, any help is more than welcome.

----

EDIT1: Also happens without CUBLAS.

----

EDIT2: I am not being able to reproduce it sometimes...

@charlyqchm, @ramirezfranciscof

**Comment by ramirezfranciscof** [comment]
Testcase?

**Comment by fedepedron** [comment]
A ferryl heme I am running with ghost atoms.
[lio.in.txt](https://github.com/MALBECC/lio/files/2493452/lio.in.txt)
[coords.xyz.txt](https://github.com/MALBECC/lio/files/2493453/coords.xyz.txt)

**Comment by ramirezfranciscof** [comment]
Was this solved in the last fix?

**Comment by fedepedron** [comment]
Seems to be solved, but I wouldn't be so sure. I'll close this for now, and reopen it if something happens.
