### ISSUE TITLE
OpenShell is broken in RC

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#54]
Does somebody know where is the problem with this?

**Comment by nanolebrero** [comment]
I do know.

2015-09-15 11:43 GMT-03:00 ramirezfranciscof <notifications@github.com>:

**Comment by ramirezfranciscof** [comment]
Follow up question then: Can you fix it?

**Comment by nanolebrero** [comment]
probably...

2015-09-15 12:58 GMT-03:00 ramirezfranciscof <notifications@github.com>:

**Comment by ramirezfranciscof** [comment]
Follow up question: is this something you are going to do in the near future?

**Comment by nanolebrero** [comment]
Soon.

**Comment by fedepedron** [comment]
> Soon.
Almost two years later, now open shell is partially working in RC. Multithreading is still not supported.

**Comment by fedepedron** [comment]
Glad to say this is finally working, I'll be closing this issue.
