### ISSUE TITLE
dynamic memory for ng0 and ngd0

### ISSUE THREAD

**Issue by Nick-Chaos** [MALBECC/lio#60]
Lio tiene problemas para sistemas grandes ya que ng2 supera la representacion de un integer por variables sobredimensionadas.

**Comment by nanolebrero** [comment]
ng2 dimensiona RMM que es un array que contiene muchas matrices diferentes (heredado de el codigo en fortran 77 sin memoria dinámica). Habría que poner cada matriz en un array separado, pero requiere de mucho test porque es usado por casi todas las subrutinas.

**Comment by Nick-Chaos** [comment]
la dimension de RMM ya es dinamica, luego de poner capa abierta partire RMM en arrays mas pequeños
