### ISSUE TITLE
New workflow for development

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#65]
- [x] Decide name for the group's organization.
- [x] Create the [organization account](https://github.com/blog/674-introducing-organizations) on Github.
- [x] Migrate lio repository from nano's account to the organization's.
- [x] Make sure all known developers fork the distribution to their accounts.
- [x] Make sure all known developers [update their local configurations](https://help.github.com/articles/changing-a-remote-s-url/).
- [x] Clean up branches in the main repository.
- [x] Update the wiki to describe new workflow.

The basic idea is to have the main repository in the organization's page with only the most basic branches (master, beta/rc, develop). Contributors would fork their own repositories and send pull request whenever they want new code to be incorporated to lio. The new code should be reviewed by the other members of the organizations.

**Comment by ramirezfranciscof** [comment]
Ok, I don't think I can come up with anything better. LioProject is an acceptable name? @nanolebrero

**Comment by nanolebrero** [comment]
No, we need a name for the organization not for the project.
GMM (Group of molecular modeling) is not good enough?
We have time to think a litle more.

2016-12-26 14:54 GMT-03:00 ramirezfranciscof <notifications@github.com>:

**Comment by emocskos** [comment]
I suggest including a distinctive and fancy name, something like Group
for Development Massive Parallel Molecular Simulation Tools...
Esteban

**Comment by Nick-Chaos** [comment]
I like gmm, but actually lio developers group include more people than gmm. 
I suggest QuMMPa (Quantum Molecular Massive Paralelization)

**Comment by emocskos** [comment]
+1

**Comment by fedepedron** [comment]
I actually like it!

**Comment by ramirezfranciscof** [comment]
@emocskos you can actually "+1/like" the comment, there is a smilie in the upper right corner of the box. Why would github include such an option is beyond my understanding.

Back on topic: an email was already sent to our mailing list to get ideas for the name, but so far no one has replied. The deadline was the 2nd of January, if no one sends something good by then, we can declare @Nick-Chaos the winner of the Malbec (prize for the chosen name).

**Comment by ramirezfranciscof** [comment]
**DISCLAIMER:** I did not notice at first and I don't know if this was the intent, but it has been brought to our attention that due to an intensive usage of that expression by certain local political/social groups, a name like that might be interpreted as an ideological statement. This may carry the drawbacks/improprieties associated with imprinting such iconic symbolism into a group whose activity is unrelated and composition more heterogeneous.

**Comment by nanolebrero** [comment]
Viva Perón!

2016-12-28 14:24 GMT-03:00 ramirezfranciscof <notifications@github.com>:

**Comment by nanolebrero** [comment]
Gacias Fran, tengo tres nombres herrrrmosssos!

Programing Engine for Reserch On Nature (PERON)
o
Chemistry Faculty Kind (CFK)
o
Eclectic and Versatile Interdisciplinary Team from Argentine (EVITA)

2016-12-28 14:52 GMT-03:00 Mariano Camilo González Lebrero <
nanolebrero@gmail.com>:

**Comment by emocskos** [comment]
I was at one second to send a not-so-nice-comment, but I need to clarify
that I'm on vacations with my family in the Neuquenian Caribe Beach...
so just answering the mails, not using anything more fancy than that.

Cheers

**Comment by nanolebrero** [comment]
Solo para los registros, yo no pedi un nombre mas "neutral", lo " neutral"
me infla los gobelins casi tanto como andar discutiendo estas boludeces en
ingles.
Mi voto sigue estando con QuMMPA.

**Comment by Nick-Chaos** [comment]
like!
(at least this force me to use my poor english skills)

Dario sugestion s:
MALBEC
Molecular argentinian laboratory buiding excellence codes
Modeling argentinian laboratory building electronic codes
 
MALBECC
Modeling argentinian laboratory building excellence chemistry codes

**Comment by ramirezfranciscof** [comment]
My apologies for any offense given to the directors of the group, none was meant. From now on I will abstain from commenting about the subject so as not to cause any further annoyance. Please do let me know once you have chosen the name so I can proceed with the migration.

**Comment by fedepedron** [comment]
I see Nick and Fran successfully managed to perform a pull-request/code revision, so I believe is past time we decided on the name for the repo's organization. I'd personally go with Dario's suggestion (MALBECC - Modeling Argentinian Laboratory Building Excellence Chemistry Codes) unless someone deems a better option (at least one that does not reflect the drinking habits of the group haha).

**Comment by ramirezfranciscof** [comment]
Organization created and repository has been moved; please everybody should change their settings in order to reflect this in **all and each** of your local repositories. Run `git remote -v` to see if you have the origin and upstream remotes. If you have both, now run:

```` git remote set-url origin https://github.com/USERNAME/lio.git
```` git remote set-url upstream https://github.com/MALBECC/lio.git

If you only have origin, then run:

```` git remote set-url origin https://github.com/USERNAME/lio.git
```` git remote add upstream https://github.com/MALBECC/lio.git

If you wish to use ssh, you can replace `https://github.com/` with `git@github.com:`.

**Comment by ramirezfranciscof** [comment]
If you don't have a fork and had a branch in the main repository, what you have to do now is fork from MALBECC, then set a temporary remote to @nanolebrero 's fork which still has all the branches and pull your branch and pull it to your own fork.

````
git remote add source https://github.com/nanolebrero/lio.git
git pull source mybranch
git push -u origin mybranch
git remote rm source
````

**Comment by fedepedron** [comment]
Is there any use in keeping this issue open?
