### ISSUE TITLE
Implementing verbose levels and output.

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#66]
Main output is written in two files: *.log (errors/warnings/timers) *.out (chemical information).
Verbose should be an integer variable. =0 prints only errors/warnings. Values 1-4 are reserved for user-available data, while values 5 and upper include develop/debug information.

Taken from issue #63: *.out file should not be overwritten, but appended to write new information.
Taken from issue #59: Lio density restart name different from default should automatically set VCINP=T.

**Comment by ramirezfranciscof** [comment]
For further research: when compiling with gfortran, write(6,*) and write(*,*) will output to the same unit, but when compiling with intel write(6,*) outputs to the .out of amber.

Case found: SCF 'converged at n iterations' message will be written in different places according to compiler used.

**Comment by fedepedron** [comment]
If I recall correctly, some units have specific meanings in gfortran, we should avoid using them if possible.

EDIT:
"Standard FORTRAN reserves two UNIT numbers for I/O to user. They are:
     UNIT = 5   for INPUT from the keyboard with the READ statement
     UNIT = 6   for OUTPUT to the screen with the WRITE statement "

source: [](http://www.oc.nps.edu/~bird/oc3030_online/fortran/io/io.html)

**Comment by ramirezfranciscof** [comment]
Ok, interesting, I didn't know about the 101-102, we should have it in mind. However, I don't know how to reconcile what you say in edit1 with what is actually happening when you compile with intel: write(6,*) is effectively outputting in a file. Unless reserve doesn't mean "you won't be allowed to use them" but "you should not use them", in which case it would seem that the amber people are the ones kind of breaking the rules here...

**Comment by fedepedron** [comment]
I arrived to the same conclusion: Intel compiler seems to keep units even between different libraries, while gfortran does not. However, there is still a workaround: If we somehow provide LIO with the AMBER output filename, then it's just a matter of opening that file from LIO as an append.

**Comment by ramirezfranciscof** [comment]
But why would we want to write in amber's output? I think it would be better that we write our own files separated from amber's. Actually, what I find most annoying is fact that they seem to have redirected unit 6 to a file, which manifests with intel's compiling behaviour.

**Comment by fedepedron** [comment]
No problem then, I thought you wanted to write to AMBER's log file; in fact I also believe that outputs should be kept separate.

**Comment by fedepedron** [comment]
Reviving this issue due to my tiredness of seeing gigantic nohup files. I'll soon start working on this, so I propose the following verbose levels:

0: Nothing
1: Lio Welcome. Total Energy. Maybe reprint chosen options?
2: Total Energy per iteration step, and total energy afterwards.
3: Energies per type and timers.
4: Empty.
5. Empty.

I believe the default should be 0 when called from amber/gromacs and 2 when called from liosolo. Please share your thoughts.

@ramirezfranciscof @nanolebrero @Nick-Chaos @williamagudelo82 @manuelF

**Comment by ramirezfranciscof** [comment]
@fedepedron we should review this when you come back.

**Comment by fedepedron** [comment]
Indeed my friend, indeed.

**Comment by fedepedron** [comment]
New scheme:
0: Nothing
1: Total energy, number of steps, convergence criteria.
2: Total energy and convergence criteria per iteration step, and total energy afterwards.
3: Energies per type, other useful data. LIO welcome 
4: Timers, analytics.
5. Debug information.

**Comment by ramirezfranciscof** [comment]
I'm finding the LIO welcome being in the lvl=3 a completely random thing. Why not in lvl=1???

**Comment by ramirezfranciscof** [comment]
I'm finding the LIO welcome being in the lvl=3 a completely random thing. Why not in lvl=1???
