### ISSUE TITLE
Cleaning up Input variables.

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#72]
I am currently writing a section of the manual containing input variables, and I found some things worth noting:

1) allnml currently does nothing.
2) Isn't it a bit redundant to have both NUNP and OPEN variables? It could be just arranged as "if nunp>0 then open=true".

**Comment by ramirezfranciscof** [comment]
I'm not an expert in this, but aren't there cases in which one would still want to run an open shell calculation with spin = 0?

**Comment by nanolebrero** [comment]
Yes, you can perform open shell calcularion with nump=0.

**Comment by fedepedron** [comment]
This issue is solved, closing it.
