### ISSUE TITLE
Compilation flags cleanup

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#75]
We talked about simplifying and reorginizing the compilations flag and discussed some particulars ( issue #66 ) but I think we didn't agreed on an overall scheme. I propose the following ideas:

* **cuda:** 0 doesn't use gpu; 1 uses cuda subs; 2 uses cuda and cublas. If this seems like one option too many, perhaps we could have only 0 or 1 (1 activating all possible gpu tools), which would require that the user has cublas installed to use any gpu optimization. Since these are free libs (as far as I know) perhaps it would not be so restrictive to require them for gpu usage.

* **parallel:** 0 doesn't use parallelization; 1 uses openMP: 2 uses MPI (to be added "soon"); 3 uses both.

* **debug:** 0 means no debug and maximum optimization (-O3, vectorization, etc); 1 means no optimization at all; 2 means use debug flags; 3 use debug flags + internal code options we might add. Perhaps we could do without 2 and have 3 directly.

* **intel**: 0 means use GNU compilers+libs; 1 means use intel compiler; 2 means intel+MKL. I am assuming the MKL make a big difference in performance. If this stops being the case, perhaps we could ditch them.

* **precision:** 0 means use mixed precision, 1 means use full double.

* **verbose:** initially, as explained in issue #66 . However, I am wondering if this doesn't overlap a little with "debug", specially when talking about the values of 5 and above. Perhaps to reconcile this the idea would be that debug tells you what to "calculate" and verbose what to "print out", but it still not very convincing because a dependency still exists (you can't print out what you haven't calculated). Also, do the verbose levels of 5 and above imply the previous ones? (that is to say, if level is 5 it will also print user data that comes with level 3). Below I present an idea to deal with this.

<br>

## Deprecated flags:

* **dbg** is now debug and is more complete.
* **cpu** redundant with cuda?
* **profile** included in debug.
* **full_double** is now precision
* **cpu_recompute:** I am not sure what is the idea of this...
* **time:** not sure what to do with this one, but having one flag just to enable/disable timers seems kind of a waste. I think ultimately it's fate will depend on how we resolve the "verbose" flag. See below.

<br>

## Verbose conflict:

Perhaps we don't need a verbose flag at compilation. Perhaps user information should be requested using input keywords, and programming information should be requested by using "debug" for tools that negatively affect performance (to check functionality) and a new "profile" flag that activates resource light tools that don't affect performance (such as timers) to test for efficiency.

<br>

Opinions and comments welcomed.

**Comment by fedepedron** [comment]
I agree with the options for cuda/parallel/intel/precision. In debug I'd merge options 2 and 3, while also activating timers. 

IIRC, cpu is not exactly mutually exclusive with cuda, but I believe the relevant options can be integrated with the "parallel" option. Maybe instead of "cuda" flag we should have a "mode" flag with several options?

Lastly, I think verbose should be a runtime option and not a compilation flag.

**Comment by ramirezfranciscof** [comment]
> I agree with the options for cuda/parallel/intel/precision. In debug I'd merge options 2 and 3, while also activating timers.

Mmm, please explain where you would put the timers? 0 optimizations, 1 optims+timers, 2 no-optimization, 3 all debug flags + codes? What about other flags that include profiling info for performance? would you include that in the option 1? So to speak, it would be something like this:

0 - optimized
1 - optimized + profiled
2 - non optimized
3 - non optimized + debug

> IIRC, cpu is not exactly mutually exclusive with cuda, but I believe the relevant options can be integrated with the "parallel" option. Maybe instead of "cuda" flag we should have a "mode" flag with several options?

Yes, I was not sure what was the purpose of the cpu flag. Re-reading it now, it seems like something used for comparing performance but I'm not sure we need to keep it for production code. I'm not really sure how to deal with this kind of "comparison test" flags: I know they might be useful to have around, but we don't want them polluting the compilation process. However, I wouldn't mix that with the gpu enabling flags.

**Comment by fedepedron** [comment]
> Mmm, please explain where you would put the timers? 0 optimizations, 1 optims+timers, 2 no-optimization, 3 all debug flags + codes? What about other flags that include profiling info for performance? would you include that in the option 1?

I'm not so sure, if we are going to include several profiling tools then I guess the "profile" flag should be ok, but for now it still bugs me the fact that we (will) have a separate flag only for timers. Mayhaps the four "option levels" you mentioned for debug are the cleanest choice.

**Comment by nanolebrero** [comment]
The tu tiners can be on always and print diferent reports depend on the
verbose level.
In a minimun repor level only  reports in the end of the run te averages.
I think that chad was include this capability on timers routines.

**Comment by fedepedron** [comment]
Regarding the use of timers, I made the following tests:
2.000.000  calls to an empty function -> 6.3ms
2.000.000  calls to an empty function containing a false If statement -> 6.4ms
2.000.000  calls to a function containing only a timer -> 8s

**Comment by ramirezfranciscof** [comment]
So, timer time is still small but perhaps not completely neglectable. After this tests, I would agree that the most suitable option is to use a compilation flag activation and ifdefs inside the timer subroutines.

Back to the general organization then, **cuda**, **intel**, **parallel** and **precision** would be kept as per opening post. Now for debug and profiling there are two options:

Using two flags...
* **debug:** 0 full optimization, 1 no-optimization, 2 debug flags and incode activation.
* **profile:** 0 no info, 1 timers, 2 timers plus other flags that enable profiling.

Using one flag...
* **profile:** 0 full optimization, 1 timers and profiling tools, 2 non-optimization, 3 non-optimization + debug flags activation.

An argument in favour of keeping separated debug and profile flags is that these keep options incremental. That is to say, we can check if the value is grater than to activate options progresively, and we can make sure we are running through all of them by using the max number.

**Comment by ramirezfranciscof** [comment]
So, for the time being we will be implementing **cuda**, **intel**, **parallel** and **precision** as per opening post and a debug option with the following: 0 for full optimization and profiling, 1 for full optimization (default), 2 for no optimization and basic debug options, 3 for no optimization and most annoying options.

I still have no idea what **cpu** and **cpu_compute** are, I will leave them as they are for now.

**Comment by manuelF** [comment]
CPU:
https://github.com/nanolebrero/lio/blob/ae24a00290b38e855dd7f0316276f8a34a8d612f/g2g/Makefile#L8

cpu=1 enables CPU compute of density for when you don't run with GPU. This is part of the hybrid mode of running multi-CPU+multi-GPU density (a major speedup of density)

**Comment by ramirezfranciscof** [comment]
So what would be the difference between cuda=0 and cpu=1 (or the reverse)? Also, I'm no completely sure of how this is part of the hybrid mode.

**Comment by fedepedron** [comment]
I believe this is addressed as it is. Will reopen in case this is needed.
