### ISSUE TITLE
Style Conventions - Indentation

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#80]
I think it would be a good idea to start setting some common rules regarding the style of some basic formatting of the code. Indentation seemed like a good place to start.

1) I think the best option is to have indentation be 2, 3 or 4 spaces; which of those to use I'm not decided, so opinions are more than welcome. We should avoid using a tab character because it is a special character and how it is displayed is dependant on local configurations (and thus could conflict with the next-in-line convention on line length limits). For those who, very understandably, like using tab because is easier to hit the tab key once than the space bar many times, you can configure vimrc to set the tab key to write spaces (see [here](http://vim.wikia.com/wiki/Converting_tabs_to_spaces)) and then set shift+tab to actually print tabs (see [here](http://stackoverflow.com/questions/4781070/how-to-insert-tab-character-when-expandtab-option-is-on-in-vim)).

2) The standard is to use indentation every time there is a change of scope and in every construct block (if, do, etc.). I would add that if there are two or more loops that run together with no command in the middle of them, they can have the same indentation (they are basically one loop). Continuation lines could also be indented, and I saw they recommend using different indentation (for example, twice the number of spaces than regular indentation), but here we can leave some extra space for improvisation (sometimes you may want to align things with the preceding line, for example)

3) I think preprocessor commands should be indented and treated as regular construction blocks for the purpose of content indentation. According to my experience, if the # symbol is on the first column you can add spaces between it and the command with no problems.

4) Line comments should also be indented, and I think the best way would be to use the same format as for the preprocessor (that is: use the ! symbol on the first column, and have the comment be in line with the related block of code).

Opinions?

**Comment by fedepedron** [comment]
Agreed on all items; although I believe some people also use TAB in order to get less characters per line (personally, I prefer continuation though).  
Any restrictions on how to use the ";" character? See lio_default() subroutine for an example.

**Comment by ramirezfranciscof** [comment]
> Agreed on all items; although I believe some people also use TAB in order to get less characters per line (if you ask me though, I prefer continuation).

I can understand the comfort in that, but for free format fortran the line limit is more a readability thing (see [first answer](https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/489142)) and thus the way it is displayed is more important than the "character count" of the editor. And the display of the tab character is much more erratic than perfectly stablished spaces.

>  Any restrictions on how to use the ";" character? See lio_default() subroutine for an example.

I think this is orthogonal to this subject since you wouldn't use ";" in a block construct nor a scope change. The only exception I can think of is some of my uses of "return; end sub", but since I have discovered that the return statement is actually unnecessary, those are soon to be gone.

**Comment by ramirezfranciscof** [comment]
As of now lio's official indentation unit is **3 spaces**. We will see how it turns out and revisit the subject if necessary.

**Comment by ramirezfranciscof** [comment]
As of now lio's official indentation unit is **3 spaces**. We will see how it turns out and revisit the subject if necessary.
