### ISSUE TITLE
Loss of precision in DP initializations

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#95]
@Nick-Chaos has just discovered a very important issue. Apparently, when initializing double precision numbers, if you don't specify the number itself is double precision, it will be **first** stored in memory as single precision and then assigned to the double precision variable. The following program exemplifies this behavior:

    program testdouble
       double precision :: rnum
       rnum = 0.1234567890123456789
       print*,rnum
       rnum = 0.1234567890123456789d0
       print*,rnum
    end program

The result is:

    0.12345679104328156     
    0.12345678901234568     
             ^
            loss of precision here

**Comment by fedepedron** [comment]
I believe this has been fixed throughout the whole fortran code, will reopen in case it happens again.
